/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Brand, Category, Vehicle, BlogPost } from "./types";

export const BRANDS: Brand[] = [
  {
    id: "lamborghini",
    name: "Lamborghini",
    logo: "⚡",
    founded: "1963",
    country: "Italy",
    story: "Founded by Ferruccio Lamborghini in 1963 to compete with established marques, Lamborghini is renowned for producing extreme, uncompromising, and highly stylized supercars and hypercars. Based in Sant'Agata Bolognese, the brand embodies pure Italian passion and cutting-edge naturally aspirated performance paired with pioneering hybrid technology.",
    featuredImg: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=1200",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    logo: "🐎",
    founded: "1939",
    country: "Italy",
    story: "The pinnacle of motor racing heritage. Founded by Enzo Ferrari, the Scuderia embodies the ultimate translation of track technology directly to the road. Driving a Ferrari is not simply about speed; it is an immersive multisensory experience, an orchestral engine note, and a timeless symbol of prestige, elegance, and extreme performance.",
    featuredImg: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1200",
  },
  {
    id: "porsche",
    name: "Porsche",
    logo: "🛡️",
    founded: "1931",
    country: "Germany",
    story: "Engineered for perfection. Porsche stands for standard-setting vehicle physics, extreme precision driving dynamics, and everyday usability. The Stuttgart-based manufacturer produces some of the most sought-after sports cars on earth, led by the evergreen legendary 911 rear-engine platform and their cutting-edge track-honed RS series.",
    featuredImg: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200",
  },
  {
    id: "rolls-royce",
    name: "Rolls-Royce",
    logo: "⚜️",
    founded: "1904",
    country: "United Kingdom",
    story: "The ultimate definition of floating luxury. Rolls-Royce manufactures motor vehicles that act as whispering sanctuaries, blending effortless V12 engines with bespoke craftsmanship and starlight headliners. Striving for absolute perfection, the brand represents the choice of kings, magnates, and connoisseurs of ultimate luxury.",
    featuredImg: "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=1200",
  },
  {
    id: "bugatti",
    name: "Bugatti",
    logo: "🌀",
    founded: "1909",
    country: "France",
    story: "If comparable, it is no longer Bugatti. Founded by Ettore Bugatti, the Alsatian brand crafts hypercars that break the boundaries of physics. Fusing multi-million-dollar rolling art forms with quad-turbocharged 16-cylinder powerhouses, they represent the absolute peak of high-velocity automotive achievements.",
    featuredImg: "https://images.unsplash.com/photo-1600706432502-75a0e2b4eed6?q=80&w=1200",
  },
  {
    id: "mclaren",
    name: "McLaren",
    logo: "🟠",
    founded: "1963",
    country: "United Kingdom",
    story: "Born in Formula One racing. McLaren Automotive utilizes advanced carbon-fibre monocells and aerodynamic design to construct superlight, driver-centric machines. Designed without compromise, each vehicle represents a pure, intense connection between driver and tarmac.",
    featuredImg: "https://images.unsplash.com/photo-1562591176-a2924345ada8?q=80&w=1200",
  },
  {
    id: "bentley",
    name: "Bentley",
    logo: "🦅",
    founded: "1919",
    country: "United Kingdom",
    story: "Perfect marriage of exhilarating power and exquisite craftsmanship. Bentley motors are built for high-performance grand touring. Seamlessly crossing continents at 200 mph in absolute luxury, they represent high-end speed combined with hand-stitched leather and premium wood veneers.",
    featuredImg: "https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=1200",
  },
  {
    id: "aston-martin",
    name: "Aston Martin",
    logo: "👐",
    founded: "1913",
    country: "United Kingdom",
    story: "Timeless British elegance, dramatic styling, and a roaring V12 soundtrack. Aston Martin fuses iconic design, high luxury, and cinematic performance, acting as the premium standard for grand touring sports cars.",
    featuredImg: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=1200",
  },
];

export const CATEGORIES: Category[] = [
  {
    id: "hypercar",
    name: "Hypercar",
    description: "The peak of velocity, high-tech engineering, and multi-million-dollar rarity.",
    icon: "☄️",
    img: "https://images.unsplash.com/photo-1600706432502-75a0e2b4eed6?q=80&w=600",
  },
  {
    id: "supercar",
    name: "Supercar",
    description: "Exquisite performance, mid-engine layouts, and breathtaking Italian design.",
    icon: "🔥",
    img: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=600",
  },
  {
    id: "sports-car",
    name: "Sports Car",
    description: "Precision handling, light curb weight, and maximum driving engagement.",
    icon: "🏁",
    img: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=600",
  },
  {
    id: "luxury-suv",
    name: "Luxury SUV",
    description: "Go-anywhere capability wrapped in whisper-quiet elegance and supreme space.",
    icon: "⛰️",
    img: "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=600",
  },
  {
    id: "convertible",
    name: "Convertible",
    description: "Open-air theatre, premium luxury wind-in-the-hair grand touring dynamics.",
    icon: "🌅",
    img: "https://images.unsplash.com/photo-1611245051065-27663e2c608f?q=80&w=600",
  },
  {
    id: "coupe",
    name: "Coupe",
    description: "Classic sleek fastback silhouettes paired with dynamic touring luxury.",
    icon: "💫",
    img: "https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=600",
  },
  {
    id: "sedan",
    name: "Sedan",
    description: "Stately cruising cabins designed specifically for high-class business travel.",
    icon: "🏛️",
    img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600",
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: "veh-1",
    brand: "Lamborghini",
    model: "Revuelto",
    year: 2025,
    price: 680000,
    mileage: 420,
    fuelType: "Hybrid",
    transmission: "Dual-Clutch",
    bodyType: "Hypercar",
    engine: "6.5L Naturally Aspirated V12 + 3 Electric Motors",
    power: "1,001 HP",
    acceleration: "0-60 mph in 2.5s",
    topSpeed: "217 mph",
    color: "Arancio Apodis (Orange Metallic)",
    interiorColor: "Nero Ade with Arancio Contrasts",
    location: "Beverly Hills, USA",
    description: "The Lamborghini Revuelto is the first super sports V12 hybrid plug-in HPEV (High Performance Electrified Vehicle). It defines a new paradigm in terms of performance, sportiness and driving pleasure from its unprecedented architecture, active aerodynamics, and full carbon chassis. Powered by a thunderous naturally aspirated V12 combined with three electric motors producing a combined 1,001 horsepower.",
    images: [
      "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=1200",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200",
      "https://images.unsplash.com/photo-1621259182978-f09e5e2b07ae?q=80&w=1200"
    ],
    sellerId: "seller-1",
    sellerName: "Aura Elite Direct",
    sellerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150",
    sellerRating: 4.9,
    views: 4520,
    inquiries: 34,
    status: "Active",
    isFeatured: true,
  },
  {
    id: "veh-2",
    brand: "Ferrari",
    model: "SF90 Stradale Assetto Fiorano",
    year: 2024,
    price: 595000,
    mileage: 890,
    fuelType: "Hybrid",
    transmission: "Dual-Clutch",
    bodyType: "Supercar",
    engine: "4.0L Twin-Turbo V8 + 3 Electric Motors",
    power: "986 HP",
    acceleration: "0-60 mph in 2.4s",
    topSpeed: "211 mph",
    color: "Rosso Corsa (Classic Racing Red)",
    interiorColor: "Carbon Racing Seats in Nero Alcantara",
    location: "Monaco",
    description: "Equipped with the upgraded Assetto Fiorano lightweight track package, this SF90 Stradale features carbon-fibre doors and underbody panels, titanium springs, and a high-downforce carbon rear spoiler. Combining a roaring twin-turbo V8 with three electric motors, it represents the absolute technological peak of Maranello performance.",
    images: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1200",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1200",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200"
    ],
    sellerId: "seller-2",
    sellerName: "Monte Carlo Prestige",
    sellerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150",
    sellerRating: 5.0,
    views: 3210,
    inquiries: 19,
    status: "Active",
    isFeatured: true,
  },
  {
    id: "veh-3",
    brand: "Bugatti",
    model: "Chiron Super Sport",
    year: 2023,
    price: 3850000,
    mileage: 180,
    fuelType: "Petrol",
    transmission: "Dual-Clutch",
    bodyType: "Hypercar",
    engine: "8.0L Quad-Turbocharged W16",
    power: "1,578 HP",
    acceleration: "0-60 mph in 2.2s",
    topSpeed: "273 mph",
    color: "Bleu de France (Visible Carbon Visual)",
    interiorColor: "Terre D’Or (Tan Full Gain Leather)",
    location: "Zurich, Switzerland",
    description: "An absolute masterpiece of automotive physics. The Chiron Super Sport represents the ultimate form of touring grand cruising velocity. With 1,578 horsepower generated from its legendary quad-turbo W16, it crosses borders at unmatched hyper-speeds. This specific chassis features a custom $400k options checklist including fully exposed blue carbon skin.",
    images: [
      "https://images.unsplash.com/photo-1600706432502-75a0e2b4eed6?q=80&w=1200",
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200"
    ],
    sellerId: "seller-3",
    sellerName: "Kronos Hyper Gallery",
    sellerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150",
    sellerRating: 4.9,
    views: 12400,
    inquiries: 48,
    status: "Active",
    isFeatured: true,
  },
  {
    id: "veh-4",
    brand: "Porsche",
    model: "911 GT3 RS (992)",
    year: 2024,
    price: 365000,
    mileage: 1200,
    fuelType: "Petrol",
    transmission: "Dual-Clutch",
    bodyType: "Sports Car",
    engine: "4.0L Naturally Aspirated Boxer-6",
    power: "518 HP",
    acceleration: "0-60 mph in 3.0s",
    topSpeed: "184 mph",
    color: "Weissach Green with Carmine Accents",
    interiorColor: "Nero Race-Tex Carbon Bucket Seats",
    location: "Munich, Germany",
    description: "The most aerodynamic track-focused street-legal car ever devised. Boasting a massive DRS-enabled rear wing, central radiator design, and dynamic steering suspension adjustments made directly from the wheel knobs, the 912 GT3 RS is built to obliterate track lap records.",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200"
    ],
    sellerId: "seller-4",
    sellerName: "Munich Autobahn Group",
    sellerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150",
    sellerRating: 4.8,
    views: 6540,
    inquiries: 42,
    status: "Active",
    isFeatured: false,
  },
  {
    id: "veh-5",
    brand: "Rolls-Royce",
    model: "Phantom Series II",
    year: 2024,
    price: 520000,
    mileage: 450,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    engine: "6.75L Twin-Turbo V12",
    power: "563 HP",
    acceleration: "0-60 mph in 5.1s",
    topSpeed: "155 mph",
    color: "Tempest Grey with Coachline Gold",
    interiorColor: "Grace White Premium Hide with Santos Veneer",
    location: "London, UK",
    description: "The premier luxury carriage of the modern era. Hand-built at Goodwood, the Phantom provides absolute silence, dynamic self-leveling air ride suspension that reads the road thousands of times per minute, and a bespoke gallery dashboard layout showcasing artisanal sculpture work.",
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=1200",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1200"
    ],
    sellerId: "seller-5",
    sellerName: "Mayfair Sovereign Lounge",
    sellerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150",
    sellerRating: 5.0,
    views: 1890,
    inquiries: 8,
    status: "Active",
    isFeatured: false,
  },
  {
    id: "veh-6",
    brand: "McLaren",
    model: "750S Spider",
    year: 2025,
    price: 345000,
    mileage: 15,
    fuelType: "Petrol",
    transmission: "Dual-Clutch",
    bodyType: "Convertible",
    engine: "4.0L Twin-Turbo V8",
    power: "740 HP",
    acceleration: "0-60 mph in 2.7s",
    topSpeed: "206 mph",
    color: "Ludus Blue Metallic",
    interiorColor: "Carbon Black Alcantara with Blue Accents",
    location: "Miami, Florida",
    description: "Lighter, more powerful, and highly engaging. The McLaren 750S Spider takes the benchmark-shattering performance of its predecessor and adds a folding hard-top roof that opens in under 11 seconds. Features a hydraulic proactive chassis control system for flawless poise.",
    images: [
      "https://images.unsplash.com/photo-1562591176-a2924345ada8?q=80&w=1200",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200"
    ],
    sellerId: "seller-1",
    sellerName: "Aura Elite Direct",
    sellerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150",
    sellerRating: 4.9,
    views: 2940,
    inquiries: 17,
    status: "Active",
    isFeatured: false,
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Decoding the Revuelto Hybrid V12 Powertrain",
    excerpt: "How Lamborghini synthesized three electric propulsion motors with its naturally aspirated V12 to reach 1,001 HP.",
    content: "When Lamborghini began formulating the successor to the legendary Aventador, the engineering team faced an almost impossible challenge: how to meet global emission targets while preserving the emotional high-revving theater of a naturally aspirated V12. The solution is code-named LB744, commercially launched as the Lamborghini Revuelto. Inside, we dive deep into the layout of its revolutionary transverse dual-clutch transmission mounted behind its V12, the tri-motor battery cooling layout, and how the torque-vectoring front e-axle shifts power seamlessly through corner apexes to preserve pure Italian mechanical grip.",
    author: "Massimo Torricelli",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150",
    publishDate: "May 25, 2026",
    readTime: "6 min read",
    category: "Engineering",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=800",
    views: 1240,
  },
  {
    id: "blog-2",
    title: "The Ultimate Guide to Hypercar Investment Dynamics",
    excerpt: "Analyzing the global market values of modern rolling masterpieces and predicting the next classics.",
    content: "Hypercars have matured from high-speed toys into fully fledged alternative assets. Over the last decade, iconic limited-run specimens such as the Ferrari LaFerrari, Bugatti Veyron, and Porsche 918 Spyder have exhibited steady double-digit compound annual appreciation rates. In this paper, we break down critical collector value indicators: provenance, low mileage preservation versus dynamic service logs, the historical index of V12 internal combustion versus premium electric drivetrains, and how low production limits (under 500 units worldwide) create literal bulletproof value floors.",
    author: "Victoria Sterling",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150",
    publishDate: "May 18, 2026",
    readTime: "9 min read",
    category: "Market Insights",
    image: "https://images.unsplash.com/photo-1600706432502-75a0e2b4eed6?q=80&w=800",
    views: 3102,
  },
  {
    id: "blog-3",
    title: "Behind the Gates of Rolls-Royce Goodwood Custom Atelier",
    excerpt: "Exploring the legendary bespoke atelier where the finest white-glove automotive craftsmanship on earth comes to life.",
    content: "No other motorcars carry the extreme, tailored luxury of Rolls-Royce. Built in the verdant setting of Goodwood, West Sussex, every Commission starts from a blank sheet of paper and an open-ended dialogue. This document details how artisans match wood veneers from a single fallen walnut tree structure, how 45 kilograms of premium noise-blocking insulation are injected into the chassis, and the literal 45,000 embroidery stitches needed to recreate the starlight night-sky constellations onto leather headliners.",
    author: "Alistar Cunningham",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150",
    publishDate: "April 29, 2026",
    readTime: "8 min read",
    category: "Bespoke Artistry",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=800",
    views: 954,
  }
];

export const OFF_LOCATIONS = [
  { city: "Beverly Hills", address: "9440 Wilshire Blvd, Beverly Hills, CA 90212", phone: "+1 (310) 555-0190", email: "bh@luxedrive.com" },
  { city: "Monaco", address: "2 Avenue des Spélugues, 98000 Monaco", phone: "+377 93 55 01 22", email: "mc@luxedrive.com" },
  { city: "London", address: "15-17 Berkeley Square, London W1J 6HB", phone: "+44 20 7555 0144", email: "uk@luxedrive.com" },
  { city: "Zurich", address: "Bahnhofstrasse 102, 8001 Zürich, Switzerland", phone: "+41 44 555 0180", email: "ch@luxedrive.com" }
];

export const FAQS = [
  { question: "How does LuxeDrive verify the vehicles listed?", answer: "Every vehicle listed as 'Active' or 'Featured' must go through a rigid 150-point physical and history validation procedure by a certified LuxeDrive Master Inspector. We verify paint thickness, chassis alignment, battery health (for hybrids/EVs), and service records against international digital ledgers." },
  { question: "Can I sell a vehicle outside of the United States and Europe?", answer: "Yes, LuxeDrive operates a premium global logistics network. We can facilitate secure escrow, vehicle health audits, and custom shipping container deliveries to and from any international port." },
  { question: "What financing terms are available for multi-million dollar hypercars?", answer: "Through our luxury private banking partners, we offer custom portfolio-backed lines of credit, high-asset flexible leasing (12 to 84 months), and zero-down balloon payments for qualified corporate entities and ultra-high-net-worth individuals." },
  { question: "How does the virtual 360 viewer and inspect process work?", answer: "Each listed vehicle includes high-definition orbital renders. Buyers can trigger a Live Video Inspection with our on-site team, or schedule an private, single-client showroom inspection at one of our hubs." },
  { question: "Are my personal and purchase details kept private?", answer: "Privacy is our highest priority. All premium escrow payments, owner identities, and final sales registries can be handled privately, with full NDAs in place, through our dedicated family office legal division." }
];
